name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd portfolio
          npm install

      - name: Run linter and formatter
        run: |
          cd portfolio
          npm run lint 
          npm run format

      - name: Build the project
        run: |
          cd portfolio
          sed -i '/output: "export",/a\  basePath: "/Portfolio",\n  assetPrefix: "/Portfolio",' next.config.mjs
          npm run build
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./portfolio/out
          publish_branch: gh-pages

          
          

